#pragma once

#define CADIE_MOUSE_BUTTON_1         0
#define CADIE_MOUSE_BUTTON_2         1
#define CADIE_MOUSE_BUTTON_3         2
#define CADIE_MOUSE_BUTTON_4         3
#define CADIE_MOUSE_BUTTON_5         4
#define CADIE_MOUSE_BUTTON_6         5
#define CADIE_MOUSE_BUTTON_7         6
#define CADIE_MOUSE_BUTTON_8         7
#define CADIE_MOUSE_BUTTON_LAST      CADIE_MOUSE_BUTTON_8
#define CADIE_MOUSE_BUTTON_LEFT      CADIE_MOUSE_BUTTON_1
#define CADIE_MOUSE_BUTTON_RIGHT     CADIE_MOUSE_BUTTON_2
#define CADIE_MOUSE_BUTTON_MIDDLE    CADIE_MOUSE_BUTTON_3